version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      # - run: npm install
      # - run: npm run build
  deploy:
    docker: 
      - image: circleci/node:7.10
    steps:
      - checkout
      - setup_remote_docker
      - run: docker container run \
--env AWS_ACCESS_KEY_ID=AKIAIEB3UWNZPAKRKLOQ \
--env AWS_SECRET_ACCESS_KEY=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 \
-v C:\\projects\\docker:/data \
garland/aws-cli-docker \
aws s3 sync . s3://www.typing-coacher.net --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
