version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  deploy:
    machine: true
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: bash ./deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters: 
            branches:
              only: master